config/routes.rb
Rails.application.routes.draw do
  # get 'sessions/new'
  # post 'sessions/create'
  # delete 'sessions/destroy'

  root :to => 'sessions#new'

	#resources :sessions
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  #get   '/books/assign/id',   to: 'books#assign'

  resources :people

  resources :books do
    member do
      get 'assign'
      get 'release'
    end
  end

  resources :devices do
    member do
      get 'showdevices'
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/person.rb
class Person < ApplicationRecord
	has_many :books

  #before_save { self.email = email.downcase }
  #validates :name, presence: true, length: { maximum: 50 }
  #VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  #validates :email, presence: true, length: { maximum: 255 },
   #                 format: { with: VALID_EMAIL_REGEX },
    #                uniqueness: { case_sensitive: false }

	has_secure_password
	validates :password, presence: true, length: { minimum: 4 }
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]
  before_action :confirm_logged_in

  # GET /people
  # GET /people.json
  def index
    #redirect_if_not_logged_in
    @people = Person.all
  end

  # GET /people/1
  # GET /people/1.json
  def show
    #redirect_if_not_logged_in
  end

  # GET /people/new
  def new
    #redirect_if_not_logged_in
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
    #redirect_if_not_logged_in
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @book = Book.find_by(person_id: @person.id)
    if(@book != nil)
      respond_to do |format|
        format.html { redirect_to people_url, notice: 'Person can not be deleted. Books assigned.' }
        format.json { head :no_content }
      end
    else
      @person.destroy
      respond_to do |format|
        format.html { redirect_to people_url, notice: 'Person was successfully destroyed.' }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.require(:person).permit(:empid, :name, :lastname, :phone, :login, :password, :admin)
    end
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/people/_form.html.erb
<%= form_for(person) do |f| %>
  <% if person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% person.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :empid %>
    <%= f.number_field :empid %>
  </div>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :lastname %>
    <%= f.text_field :lastname %>
  </div>

  <div class="field">
    <%= f.label :phone %>
    <%= f.number_field :phone %>
  </div>

  <div class="field">
    <%= f.label :login %>
    <%= f.text_field :login %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <%= f.text_field :password %>
  </div>

  <div class="field">
    <%= f.label :admin %>
    <%= f.check_box :admin %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/people/assign.html.erb
<h1>Editing book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', book_path %>

app/views/people/edit.html.erb
<h1>Editing Person</h1>

<%= render 'form', person: @person %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>

app/views/people/index.html.erb
<p id="notice"><%= notice %></p>

<h1>People</h1>

<table>
  <thead>
    <tr>
      <th>Empid</th>
      <th>Name</th>
      <th>Lastname</th>
      <th>Phone</th>
      <th>Login</th>
      <th>Admin</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><%= person.empid %></td>
        <td><%= person.name %></td>
        <td><%= person.lastname %></td>
        <td><%= person.phone %></td>
        <td><%= person.login %></td>
        <td><%= person.admin %></td>

        <% if is_admin? %>
          <td><%= link_to 'Show', person %></td>
          <td><%= link_to 'Edit', edit_person_path(person) %></td>
          <td><%= link_to 'Delete', person, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Person', new_person_path %>

app/views/people/new.html.erb
<h1>New Person</h1>

<%= render 'form', person: @person %>

<%= link_to 'Back', people_path %>

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Empid:</strong>
  <%= @person.empid %>
</p>

<p>
  <strong>Name:</strong>
  <%= @person.name %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @person.lastname %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @person.phone %>
</p>

<p>
  <strong>Login:</strong>
  <%= @person.login %>
</p>

<p>
  <strong>Admin:</strong>
  <%= @person.admin %>
</p>

<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Back', people_path %>