config/routes.rb
Rails.application.routes.draw do
  # get 'sessions/new'
  # post 'sessions/create'
  # delete 'sessions/destroy'

  root :to => 'sessions#new'

	#resources :sessions
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  #get   '/books/assign/id',   to: 'books#assign'

  resources :people

  resources :books do
    member do
      get 'assign'
      get 'release'
    end
  end

  resources :devices do
    member do
      get 'showdevices'
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/device.rb
class Device < ApplicationRecord
  belongs_to :person

  CATEGORY = ["Phone", "Tab"]
  LOCATION = ["ALL", "Hyderabad", "Irvine", "Nizhny"] 

end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController
  before_action :set_device, only: [:show, :edit, :update, :destroy]
  before_action :confirm_logged_in
  helper_method :getName, :getLenderName


  # GET /devices
  # GET /devices.json
  def index
    puts "***************** From index"
    @filter_location = params[:filter_location]
    @filter_owner = params[:filter_owner]

    @people = Person.pluck(:name, :id)
    @people.insert(0, "ALL")
    @location = Device::LOCATION
 
    if(@filter_location.nil?) 
      @devices = Device.all
   else
      #filter_location
      #Todo: this code needs to be refactored properly*******************
      if(@filter_location == "ALL" and @filter_owner == "ALL")
        @devices = Device.all
      else
        if (@filter_location == "ALL")
          @devices = Device.where(["person_id = ?", @filter_owner])
        else
          if (@filter_owner == "ALL")
            @devices = Device.where(["location = ?", @filter_location])
          else
            @devices = Device.where(["location = ? and person_id = ?", @filter_location, @filter_owner])
          end
        end
      end        
    end
  end

  def showdevices
    puts "***************** From filter"
    puts "From filter"
    p @filter_location
  end

  def getLenderName(pid)
    name = getName(pid) 
    if !name.empty?
      return name
    else
      "Available"
    end
  end

  def getName(pid)
    if (pid)
      Person.find_by(id: pid).name
    else
      ""
    end  
  end

  # GET /devices/1
  # GET /devices/1.json
  def show
    puts "***************** From show"
    if @device.person_id
      @person = Person.find_by(id: @device.person_id).name
      @people = Person.pluck(:name, :id)

    end
  end

  # GET /devices/new
  def new
    puts "***************** From new"
    @device = Device.new
    @people = Person.pluck(:name, :id)
    @category = Device::CATEGORY
    @location = Device::LOCATION
  end

  # GET /devices/1/edit
  def edit
    puts "***************** From edit"
      @people = Person.pluck(:name, :id)
      @category = Device::CATEGORY
      @location = Device::LOCATION
  end

  # POST /devices
  # POST /devices.json
  def create
    puts "***************** From create"
    @device = Device.new(device_params)

    respond_to do |format|
      if @device.save
        format.html { redirect_to @device, notice: 'Device was successfully created.' }
        format.json { render :show, status: :created, location: @device }
      else
        format.html { render :new }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /devices/1
  # PATCH/PUT /devices/1.json
  def update
    puts "***************** From update"
    respond_to do |format|
      if @device.update(device_params)
        format.html { redirect_to @device, notice: 'Device was successfully updated.' }
        format.json { render :show, status: :ok, location: @device }
      else
        format.html { render :edit }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /devices/1
  # DELETE /devices/1.json
  def destroy
    @device.destroy
    respond_to do |format|
      format.html { redirect_to devices_url, notice: 'Device was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_device
      puts "***************** From Set device"
      @device = Device.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def device_params
      params.require(:device).permit(:device_id, :company, :name, :lent_by, :team, :location, :category, :info, :person_id)
      #params.require(:filter_location, :filter_owner)
    end
   
    # def set_filter
    #   puts "***************** From Set Filter"
    #   @filter_location = params[:filter_location]
    #   @filter_owner = params[:filter_owner]
    # end

end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/views/devices/_filterform.html.erb
<%= form_for(people) do |f| %>

  <p>
    <strong>Filter by location:</strong>
    <%= select_tag(:filter_location, options_for_select(@location)) %>
  </p>
  <p>
    <strong>Filter by owner:</strong>
    <%= select_tag(:filter_owner, options_for_select(@people)) %>
  </p>
    
  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/devices/_form.html.erb
<%= form_for(device) do |f| %>
  <% if device.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(device.errors.count, "error") %> prohibited this device from being saved:</h2>

      <ul>
      <% device.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Owner %>
    <%= f.select :person_id, @people %>
  </div>


  <div class="field">
    <%= f.label :device_id %>
    <%= f.text_field :device_id %>
  </div>

  <div class="field">
    <%= f.label :company %>
    <%= f.text_field :company %>
  </div>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :lent_by %>
    <%= f.select :lent_by, @people %>
  </div>

  <div class="field">
    <%= f.label :location %>
    <%= f.select :location, @location %>
  </div>

  <div class="field">
    <%= f.label :category %>
    <%= f.select :category, @category %>
  </div>

  <div class="field">
    <%= f.label :info %>
    <%= f.text_field :info %>
  </div>


 <div class="actions">
    <%= f.submit %>
 </div>
<% end %>

app/views/devices/edit.html.erb
<h1>Editing Device</h1>

<%= render 'form', device: @device %>

<%= link_to 'Show', @device %> |
<%= link_to 'Back', devices_path %>

app/views/devices/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Devices</h1>


<form action='/devices' method="get">
  <p>
    <strong>Filter by location:</strong>
    <%= select_tag(:filter_location, options_for_select(@location)) %>
  </p>
  <p>
    <strong>Filter by owner:</strong>
    <%= select_tag(:filter_owner, options_for_select(@people)) %>
  </p>

  <input type="submit" />
</form>


<table>
  <thead>
    <tr>
      <th>Owner</th>
      <th>Device</th>
      <th>Company</th>
      <th>Name</th>
      <th>Lent by</th>
      <th>Location</th>
      <th>Category</th>
      <th>Info</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @devices.each do |device| %>
      <tr>
        <td><%= getName(device.person_id) %></td>
        <td><%= device.device_id %></td>
        <td><%= device.company %></td>
        <td><%= device.name %></td>
        <td><%= getLenderName(device.lent_by) %></td>
        <td><%= device.location %></td>
        <td><%= device.category %></td>
        <td><%= device.info %></td>

        <td><%= link_to 'Show', device %></td>
        <td><%= link_to 'Edit', edit_device_path(device) %></td>
        <td><%= link_to 'Delete', device, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<br>

<%= link_to 'New Device', new_device_path %>

app/views/devices/new.html.erb
<h1>New Device</h1>

<%= render 'form', device: @device, people: @people %>

<%= link_to 'Back', devices_path %>

app/views/devices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Owner:</strong>
  <%= @person %>
</p>

<p>
  <strong>Device Id:</strong>
  <%= @device.device_id %>
</p>

<p>
  <strong>Company:</strong>
  <%= @device.company %>
</p>

<p>
  <strong>Name:</strong>
  <%= @device.name %>
</p>

<p>
  <strong>Lent by:</strong>
  <%= getLenderName(@device.lent_by) %>
</p>

<p>
  <strong>Location:</strong>
  <%= @device.location %>
</p>

<p>
  <strong>Category:</strong>
  <%= @device.category %>
</p>

<p>
  <strong>Info:</strong>
  <%= @device.info %>
</p>


<%= link_to 'Edit', edit_device_path(@device) %> |
<%= link_to 'Back', devices_path %>

app/views/devices/showdevices.html.erb
<p id="notice"><%= notice %></p>

<h1>Showing Devices</h1>


<form action='/showdevices' method="get">
  <p>
    <strong>Filter by location:</strong>
    <%= select_tag(:filter_location, options_for_select(@location)) %>
  </p>
  <p>
    <strong>Filter by owner:</strong>
    <%= select_tag(:filter_owner, options_for_select(@people)) %>
  </p>

  <input type="submit" />
</form>


<table>
  <thead>
    <tr>
      <th>Owner</th>
      <th>Device</th>
      <th>Company</th>
      <th>Name</th>
      <th>Lent by</th>
      <th>Location</th>
      <th>Category</th>
      <th>Info</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @devices.each do |device| %>
      <tr>
        <td><%= getName(device.person_id) %></td>
        <td><%= device.device_id %></td>
        <td><%= device.company %></td>
        <td><%= device.name %></td>
        <td><%= getLenderName(device.lent_by) %></td>
        <td><%= device.location %></td>
        <td><%= device.category %></td>
        <td><%= device.info %></td>

        <td><%= link_to 'Show', device %></td>
        <td><%= link_to 'Edit', edit_device_path(device) %></td>
        <td><%= link_to 'Delete', device, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Device', new_device_path %>