config/routes.rb
Rails.application.routes.draw do
  # get 'sessions/new'
  # post 'sessions/create'
  # delete 'sessions/destroy'

  root :to => 'sessions#new'

	#resources :sessions
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  #get   '/books/assign/id',   to: 'books#assign'

  resources :people

  resources :books do
    member do
      get 'assign'
      get 'release'
    end
  end

  resources :devices do
    member do
      get 'showdevices'
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :person, optional: true
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy, :assign, :release]
  before_action :confirm_logged_in
  helper_method :getName, :getLenderName, :allowEdit

  # GET /books
  # GET /books.json
  def index
    #redirect_if_not_logged_in
    @books = Book.all
  end

  def assign
    puts "************Assign called"
    @people = Person.pluck(:name, :id)
  end

  def getName(pid)
    if (pid)
    	Person.find_by(id: pid).name
    else
      ""
    end  
  	#select p.name from People p where p.id = pid;
  	#select b.team, b.category, b.title, b.auther, p.name from books b, people p where b.person_id = :id;
  end

  def getLenderName(pid)
    name = getName(pid) 
    if !name.empty?
      return name
    else
      "Available"
    end
  end

  def allowEdit (pid)
    if (pid)
      is_admin? || (current_user.name == getName(pid))
    else
      is_admin?
    end

  end

  # GET /books/1
  # GET /books/1.json
  def show
    puts "************show called"
    if @book.person_id
      @person = Person.find_by(id: @book.person_id).name
      @people = Person.pluck(:name, :id)
    end
  end

  # GET /books/new
  def new
    @book = Book.new
    @people = Person.pluck(:name, :id)
    puts "*** From new "
  end

  # GET /books/1/edit
  def edit
    @people = Person.pluck(:name, :id)
  end


  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)
    puts "*** From create: " 

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    @people = Person.pluck(:name, :id)
    puts "*** From update: " 

    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def release
    puts "*** From release: " 
    @book.person_id = ""
    @book.save

    respond_to do |format|
      format.html { redirect_to @book, notice: 'Book was successfully released.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      puts "************set book called" 
      puts :id
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:team, :category, :title, :auther, :person_id)
    end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= form_for(book) do |f| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :team %>
    <%= f.text_field :team %>
  </div>

  <div class="field">
    <%= f.label :category %>
    <%= f.text_field :category %>
  </div>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :auther %>
    <%= f.text_field :auther %>
  </div>

  <div class="field">
    <%= f.label :Lent_By %>
    <%= f.select :person_id, @people %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/books/assign.html.erb
<h1>Assign Book</h1>

<%= form_for(@book) do |f| %>

  <div class="field">
  	<strong>
    <%= f.label :title %>
    </strong>
    <%= @book.title %>
  </div>


  <div class="field">
  <strong>
    <%= f.label :Lent_By %>
  <strong>
    <%= f.select :person_id, @people %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

<%= link_to 'Back', books_path %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Books</h1>

<table>
  <thead>
    <tr>
      <th>Team</th>
      <th>Category</th>
      <th>Title</th>
      <th>Auther</th>
      <th>Lent by </th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.team %></td>
        <td><%= book.category %></td>
        <td><%= book.title %></td>
        <td><%= book.auther %></td>
        <td><%= getLenderName(book.person_id) %></td>

        <% if allowEdit (book.person_id) %>
          <td><%= link_to 'Show', book %></td>
          <td><%= link_to 'Edit', edit_book_path(book) %></td>
          <td><%= link_to 'Assign', assign_book_path(book) %></td>
          <td><%= link_to 'Release', release_book_path(book) %></td>
        <% end %>

        <% if is_admin? %>
          <td><%= link_to 'Delete', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Book', new_book_path %>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form', book: @book, people: @people %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Team:</strong>
  <%= @book.team %>
</p>

<p>
  <strong>Category:</strong>
  <%= @book.category %>
</p>

<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>

<p>
  <strong>Auther:</strong>
  <%= @book.auther %>
</p>

<p>
  <strong>Person:</strong>
  <%= @person %>
</p>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>